name: 'Deploy Microservice'
description: 'Clones the repo and deploys using pm2 on Windows via CMD'
inputs:
  env_name:
    description: 'Environment name (dev, stg, preprod, prod)'
    required: true
  port:
    description: 'Application port'
    required: true
runs:
  using: "composite"
  steps:
    - name: Info output
      shell: cmd
      run: echo Deploying to ${{ inputs.env_name }} environment on port ${{ inputs.port }}...

    - name: Checkout pipeline repo
      uses: actions/checkout@v6
      with:
        clean: false

    - name: Clone Python app repo
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        clean: false

    - name: Stop existing pm2 service
      shell: cmd
      run: pm2 delete greetings-app-${{ inputs.env_name }} & EXIT /B 0

    - name: Start service with pm2
      working-directory: ./python-greetings
      shell: cmd
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter "%GITHUB_WORKSPACE%\python-greetings\venv\Scripts\python.exe" -- --port ${{ inputs.port }}

# Pagaidu tests ar extra boot laiku
    - name: Wait for service to boot
      shell: cmd
      run: timeout /t 10 /nobreak