name: 'Deploy Microservice'
description: 'Clones the repo and deploys using pm2 on Windows'
inputs:
  env_name:
    description: 'Environment name (dev, stg, preprod, prod)'
    required: true
  port:
    description: 'Application port'
    required: true
runs:
  using: "composite"
  steps:
    - name: Info output
      run: echo "Deploying to ${{ inputs.env_name }} environment on port ${{ inputs.port }}..."
      shell: powershell

    - name: Checkout pipeline repo
      uses: actions/checkout@v6

    - name: Clone Python app repo
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing pm2 service
      run: pm2 delete greetings-app-${{ inputs.env_name }} & EXIT /B 0
      shell: cmd

    - name: Start service with pm2
      working-directory: ./python-greetings
      shell: powershell
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter venv\Scripts\python.exe -- --port ${{ inputs.port }}